#ifndef EXTINTERRUPT_CONFIG_H_
#define EXTINTERRUPT_CONFIG_H_



#define INT0_EN INT_ENABLE
#define INT1_EN INT_DISABLE
#define INT2_EN INT_DISABLE


// LOW_LEVEL, LOGICAL_CHANGE, FALLING_EDGE, RISING_EDGE
#define INT0_SENSE RISING_EDGE

// LOW_LEVEL, LOGICAL_CHANGE, FALLING_EDGE, RISING_EDGE
#define INT1_SENSE RISING_EDGE

//FALLING_EDGE, RISING_EDGE
#define INT2_SENSE RISING_EDGE

#endif /* EXTINTERRUPT_CONFIG_H_*/
