#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

#define TIMER0_MODE         TIMER0_FAST_PWM_MODE
#define OC0_MODE            TIMER0_FAST_PWM_SET_OC0_AT_TOP
#define TIMER0_PRESCALER    TIMER0_PRESCALER_1


#endif /* TIMER0_CONFIG_H_*/
