#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

#define SPI_CLK_POLARITY CLK_POLARITY_IDLE_LOW
#define SPI_CLK_PHASE    CLK_PHASE_SAMPLE_LEADING_EDGE
#define SPI_PRESCALER    PRESCALER_64




#endif /* SPI_CONFIG_H_ */
